### ISSUE TITLE
Feature request: nested tables

### ISSUE THREAD

**Issue by gkholman** [drmacro/wordinator#106]
Using Word interactively I can nest a table inside of another table, per: [Nested Tables 20230215.docx](https://github.com/drmacro/wordinator/files/10751127/Nested.Tables.20230215.docx)

The SWPX schema does not allow me to put a \<table> in a \<td>. I hacked the schema to allow it, but then the program didn't support my hack.

We have a use case when converting NISO STS XML where tables are nested.

**Comment by larsga** [comment]
Do you have a sample document with nested tables? That would make this much easier to implement and test.

**Comment by larsga** [comment]
Took one of Eliot's table test cases and modified it to include a nested table. It works:

<img width="671" alt="image" src="https://user-images.githubusercontent.com/446984/219323384-84ee371f-f6f5-4730-87f9-65864d8fdec2.png">

Will turn this into a full PR.

**Comment by larsga** [comment]
Added a pull request. Waiting for review.

**Comment by drmacro** [comment]
I updated the test case to add "Nested" to the nested content to make it more obvious that the table is nested.

**Comment by drmacro** [comment]
Closing this because issue 109 covers the corrupted document issue resulting from the initial implementation of this feature.
