### ISSUE TITLE
Conversion errors with tables

### ISSUE THREAD

**Issue by larsga** [drmacro/wordinator#109]
With the changes in PR #108 Word starts complaining about tables, and has to repair converted Word documents. The error reporting looks like this:

![image](https://user-images.githubusercontent.com/446984/219599650-6849dd32-7c42-40e0-9c6c-935405541d72.png)

The user reports that "Interestingly, the new tables look better than the old because it seems my border control is being respected by the new JAR ... unless, perhaps, that is related to why Word seems to find the tables in error."

Very likely this is caused by the new code that traverses the contents of the table cell, or perhaps by differences in how garbage content added by POI is deleted.

**Comment by drmacro** [comment]
The issue as far as I can tell is that Word expects an empty paragraph following a nested table.

If I let Word repair the test doc, it adds an empty paragraph after the table within the cell.

Removing that paragraph makes the doc corrupted, restoring makes it open normally.

**Comment by drmacro** [comment]
Confirmed that if I create a nested table manually in Word it adds a trailing empty paragraph.

I don't see anything in the OOXML docs that suggest this is required but it seems to be how Word works.

**Comment by drmacro** [comment]
See https://github.com/drmacro/wordinator/pull/110

**Comment by larsga** [comment]
The cause of the problem (found by narrowing down the failing example) is empty table cells in the input.

With the old code these output:
```
      <w:tc>
        <w:tcPr><w:tcW w:type="pct" w:w="2250"/></w:tcPr>
        <w:p/>
      </w:tc>
```

With the new code they output:

```
<w:tc>
  <w:tcPr><w:tcW w:type="pct" w:w="2250"/></w:tcPr>
</w:tc>
```

Clearly Word doesn't accept the absence of a paragraph there.

**Comment by drmacro** [comment]
Fixed here: https://github.com/drmacro/wordinator/pull/137
