### ISSUE TITLE
Replace document-uri() with base-uri() in XSLTs

### ISSUE THREAD

**Issue by ekimbernow** [drmacro/wordinator#130]
From Ken H: 

Good morning, Eliot!

I've tripped over a non-backward-compatible change in Saxon, justified here:

[https://saxonica.plan.io/issues/6285](https://protect-us.mimecast.com/s/nlYlCNk6O1i0RwrOEs4zhIl?domain=saxonica.plan.io)

... and I note that document-uri(/) is used in html2docx.xsl in
Wordinator. Easy fix to use base-uri(/).

**Comment by drmacro** [comment]
Committed update to replace document-uri() with base-uri().
