### ISSUE TITLE
Bad Justification on the Last Line of the Last Paragraph in Section

### ISSUE THREAD

**Issue by rajko-furlan** [drmacro/wordinator#149]
If there is a justified paragraph at the end of a section then the last line is also justified (i.e., stretched out to fill the whole line) while it shouldn't be. This can be fixed manually by clicking at the end of that line and pressing "return". It would be nice if this were handled automatically by Wordinator somehow.

**Comment by drmacro** [comment]
This duplicates issue 105. Will use that issue to work this .
