### ISSUE TITLE
Run after <fn> truncated

### ISSUE THREAD

**Issue by rf2001** [drmacro/wordinator#3]
I've got the following structure in an swpx file:

`<p style="IASB Normal npara" styleId="IASBNormalnpara"><run>B20</run><run><tab/></run><run>To illustrate a build‑up approach, assume that Asset A is a contractual right to receive CU800</run><fn><p style="IASB Normal" styleId="IASBNormal"><run>In this IFRS monetary amounts are denominated in ‘currency units (CU)’.</run></p></fn><run> in one year (ie there is no timing uncertainty). There is an established market for comparable assets, and information about those assets, including price information, is available. Of those comparable assets:</run></p>
`

When Word is generated the `<run>` after the `<fn>` (i.e. "`<run> in one year ...`") is dropped and no text is generated. Please check the zip attached to issue (2) and search for `<fn>`. There are several `<fn>` elements. I didn't check them all, but the first two definitely exhibit the behavior described.

**Comment by drmacro** [comment]
Investigating.

**Comment by drmacro** [comment]
Fixed bug for release in version 0.9.3
