### ISSUE TITLE
Landscape pages needed

### ISSUE THREAD

**Issue by rf2001** [drmacro/wordinator#7]
Some tables are landscape tables. For those tables I'd need to be able to define a landscape page. I suppose this could be a section property, but I'm not sure. What would be the simplest way to implement this?

**Comment by drmacro** [comment]
Sections can include page layout so it should be easy enough add support for specifying the page details.

**Comment by drmacro** [comment]
Added new element `<page-size>` to the page sequence properties:
```
    <section type="nextPage">
      <page-sequence-properties>
        <page-number-properties format="lowerRoman" chapter-separator="emDash" chapter-style="1" start="99"/>
        <page-size
          height="14in"
          width="11in"
          orient="landscape"          
        />          
        
      </page-sequence-properties>
```

**Comment by rf2001** [comment]
Works fine, thanks.
