### ISSUE TITLE
Table sizings are not adhered to following implementation of #70

### ISSUE THREAD

**Issue by CallumES** [drmacro/wordinator#73]
When testing the change made for #70 , images are now successfully constrained to the detailed size however I've noticed that tables now seem to be suffering from a lack of proportions following the implementation of this change.

It can be seen in the image-geometry-test files that you uploaded whereby each column of the table has one character per line. Tables in this file are specified using % widths, is there perhaps a conflict between using px values for images and % values for tables now?

[image-geometry-test.docx (1).zip](https://github.com/drmacro/wordinator/files/9808392/image-geometry-test.docx.1.zip)

**Comment by drmacro** [comment]
Investigating.

**Comment by drmacro** [comment]
I am seeing a change in behavior from version 1.0.0 to 1.1.0 for tables--it looks like the default for the DOCX table layout changed from "auto" to "fixed", which causes tables that do not specify explicit widths to be rendered as narrowly as possible.

Investigating.

**Comment by drmacro** [comment]
The change was implemented as a result of #49, which added always setting the table layout property with a default of "fixed". Before this the effective default was "auto".

I think the correct fix is to make the default table layout be "auto". 

You can work around this behavior by explicitly setting layout="auto" on the HTML or SWPX table.

**Comment by drmacro** [comment]
I've committed the fix to develop branch.

Please verify on your end that tables with no @layout value produce the expected result.

**Comment by drmacro** [comment]
Fixed
