### ISSUE TITLE
Feature request: image data from embedded Base64

### ISSUE THREAD

**Issue by gkholman** [drmacro/wordinator#79]
My XHTML that I am transforming into SWPX embeds all graphics as follows:
```
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUh...XXa7Z"/>
```
There is no resolvable URI with which an image file can be dereferenced using the `http:` scheme.

It would be handy if wp:image would support the `data:` scheme in the src= attribute. No file management necessary. The reason I have it in my HTML is so that the HTML is a single monolithic file and not an unmanageable collection of graphics.

I would simply copy my HTML src= attribute into my SWPX src= attribute and that job would be done.

**Comment by ekimbernow** [comment]
This is implemented in release 1.1.1
